In [16]:
import torch
import numpy as np

In [4]:
x = [12, 23,34,45,56,67,78]
torch.is_tensor(x)
torch.is_storage(x)

False

In [9]:
y = torch.randn(1,2,3,4,5)
torch.numel(y) # total number of elements in the tensor
torch.zeros(4,4,4) # matrix of all zeros
torch.eye(4,4) # Identity matrix
torch.from_numpy(np.random.rand(4,4)) # generate tensors from numpy array
torch.linspace(2, 10, steps=20) # linear spacing
torch.logspace(start=-10, end=10, steps=30) # log spacing
torch.rand(10) # random numbers between 0 and 1
torch.rand(5,5)
torch.randn(10) # random numbers from a normal distribution with mean=0, sd=1
torch.randn(5,5)
torch.randperm(20) # random permutation of selected values from a range(10)
torch.arange(10) # list of range of numbers steps by 1
torch.arange(10, 50, 2) # list of range of numbers steps by 2
torch.argmin(torch.randn(20, 10), dim=0) # find the index of the minimum number in the matrix along the x axis
torch.argmax(torch.randn(20, 10), dim=1) # find the index of the maximum number in the matrix along the y axis
torch.cat((torch.randn(5,5), torch.randn(5,5)), dim=0) # concatenate two tensors ~ vstack
torch.chunk(torch.randn(6,6), 2, dim=1) # splitting a tensor into chunks along dim
torch.gather(torch.Tensor([[10, 12],[13,14]]), 1, torch.LongTensor([[0,0],[1,0]])) # gather elements of a tensor by index; can be used to shuffle or maxpool
# torch.index_select(matrix, dim, indeces)
torch.nonzero(torch.tensor([10, 0, 23, 0, 0.0])) # select the indices of non zero elements of a tensor
torch.split(torch.tensor([12,21,38,32,45,58,63]), 3) # split a tensor into specified number of tensors
torch.rand(4,3).t() # transpose of a tensor
torch.unbind(torch.randn(5,4), 0) # loose a tensor up along a dim into tupple of tensors
torch.add(torch.randn(5,4), torch.ones(5,4))
torch.mul(torch.rand(5,4), 2) # scalar multiplication
torch.manual_seed(12)
torch.ceil(torch.randn(5,4)) # round up elements of a tensor
torch.floor(torch.randn(5,4)) # round down elements of a tensor
torch.clamp(torch.randn(6,6), min=0.1) # truncate a lower limit of an array
torch.clamp(torch.randn(6,6), max=0.1) # truncate a upper limit of an array
torch.exp(torch.rand(2,2)) # exponentiation of a tensor
torch.frac(torch.rand(3,3)) # get the fractional portion of a matrix element
torch.log(torch.rand(3,3))
torch.pow(torch.rand(3,3), 2)
torch.sigmoid(torch.rand(3,3))
torch.sqrt(torch.rand(3,3))

120

In [97]:
torch.Tensor(5,5).uniform_(0,1) # random 5,5 array from a uniform random distribution between 0 and 1
torch.bernoulli(torch.Tensor(3,3).uniform_(0,1)) # compute bernoulli sample from a uniform distribution samples
torch.multinomial(torch.randperm(16, dtype=torch.float64), 4, replacement=True) # select sample from a multinomial distribution
torch.normal(mean=0.5, std=torch.arange(0., 7.)) # generate multivariate normal distribution with same mean

tensor([0.5000, 0.7119, 0.5014, 1.7898, 4.2058, 4.7922, 0.8954])

In [104]:
torch.mean(torch.rand(5,5))
torch.median(torch.rand(5,5))
torch.mode(torch.rand(3,3))
torch.std(torch.rand(3,3), dim=1)
torch.var(torch.rand(3,3), dim=0)

tensor([0.1470, 0.0143, 0.2049])

In [110]:
from torch.distributions import Laplace
dist = Laplace(torch.tensor([10.0]), torch.tensor([0.990]))
dist.sample()

tensor([8.8965])

In [111]:
from torch.distributions import Bernoulli
dist = Bernoulli(torch.tensor([0.3, 0.6, 0.9]))
dist.sample()

tensor([0., 0., 1.])

In [112]:
from torch.distributions import Categorical
dist = Categorical(torch.tensor([.2, .2, .2, .2, .2]))
dist.sample()

tensor(4)

In [113]:
from torch.distributions import Binomial
dist = Binomial(50, torch.tensor([0.2, 0.5, 0.8, 1]))
dist.sample()

tensor([12., 21., 44., 50.])

In [114]:
from torch.distributions.normal import Normal
dist = Normal(torch.tensor([10.]), torch.tensor([2.]))
dist.sample()

tensor([7.5891])

In [115]:
from torch.distributions import Beta
dist = Beta(torch.tensor([0.3]), torch.tensor([0.2]))
dist.sample()


tensor([0.9987])